language: node_js

node_js:
 - "node"
env:
 global: CC_TEST_REPORTER_ID=553b2a432516282dcbf1cec624843364f4a2fc72401672bbe2b7d2d837d77907


before_script:
   - cd api
   - npm install
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
   - ./cc-test-reporter before-build
script:
 - npm test
 - npm run coverage
after_success:
   - coveralls
   - npm run coverage
   - cd
   - codeclimate-test-reporter < coverage/lcov.info
after_script:
   - ./node_modules/.bin/mocha YOUR_TESTS/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT