language: node_js
node_js:
- "stable"
before_install: cd api/
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
- npm test
after_success:
- npm run coverage
- npm run coveralls
- npm run report-coverage
-./node_modules/.bin/mocha